name: Build and Store Gradle JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
          gradle-version: 8.5
    - run: gradle build -x test
    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
          name: CargaMaterias
          path: build/libs/carga_materias_demo-0.0.1-SNAPSHOT.jar
          
